name: Mirror Repository

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    environment: mirror
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to mirror

        env:
            TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git remote add mirror https://ConciencIAs:$TOKEN@github.com/ConciencIAs/mirror-zona-green.git
          git push --mirror mirror
